### ISSUE TITLE
@energy is picky 

### ISSUE THREAD

**Issue by gustavojra** [FermiQC/Fermi.jl#26]
```
@energy CCSD(T)
```

Will not work because characters like `()` are removed during the `Expr` -> `String` convertion.

**Comment by mdav2** [comment]
Do we have an idea of how to fix this?

**Comment by gustavojra** [comment]
Yes, I just have to rework how the Expr -> String conversion is taking place

**Comment by gustavojra** [comment]
Fixed #39
