### ISSUE TITLE
Mysterious parameter in the RHF code

### ISSUE THREAD

**Issue by gustavojra** [FermiQC/Fermi.jl#41]
```
function RHF(molecule::Molecule, aoint::IntegralHelper, C::Array{Float64,2}, Λ, Alg::ConventionalRHF)
    @output "Computing integrals ..."
    t = @elapsed aoint["μ"]
    @output " done in {:>5.2f} s\n" t
    RHF(molecule,aoint,C,aoint["μ"],Λ)
end
function RHF(molecule::Molecule, aoint::IntegralHelper, C::Array{Float64,2}, Λ, Alg::DFRHF)
    @output "Computing integrals ..."
    t = @elapsed aoint["B"]
    @output " done in {:>5.2f} s\n" t
    RHF(molecule,aoint,C,aoint["B"],Λ)
end
```

This Λ needs some specification, right now this method will accept anything for Λ. Also some clarification on what is that via docs or comment would be nice.

**Comment by mdav2** [comment]
Okay yeah. It's the orthogonalizer, which I moved out of the RHF kernel so we could choose symmetric vs. canonical orthogonalization.

**Comment by mdav2** [comment]
I think we should just always use canonical though, its more stable for near-linearly dependent cases.

**Comment by gustavojra** [comment]
Solved with refactorization
